version: '3.1'
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    restart : unless-stopped
    networks:
      - backend
  express:
    container_name: express
    image: ream123/aiez-server:latest
    environment:
      - DB_HOST=root
      - DB_PASSWOD=password
      - MONGO_URL=mongo:27017/aiez
      - COOKIE_SECRET=kJ`+=Mj3t}<*8A6fuW{z9}z16iqxC3
    ports:
      - 4000:4000
    networks:
      - backend
    depends_on:
      - mongo
    restart : unless-stopped
  react:
    container_name: react
    stdin_open: true
    build:
      context: ../aiez-client
    ports:
      - 3000:3000
    networks:
      - backend
    depends_on:
      - express
      - mongo
    restart : unless-stopped
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./volume:/data/db
    networks:
      - backend
    restart : unless-stopped
    healthcheck:
      test: "pg_isready -h localhost -p 27017 -U mongo"
      interval: 3s
      timeout: 1s
      retries: 10
networks:
  backend:
    driver: bridge
