version: '3.1' 
services:
  proxy:
    image: nginx:latest
    container_name: proxy
    ports:
      - 80:80
    volumes:
      - /nginx.conf:/etc/nginx/nginx.conf
    restart : unless-stopped
    networks:
      - backend
  express:
    container_name: express
    image: /home/ubuntu/aiez-server
    environment:
      - DB_HOST=root
      - DB_PASSWOD=password
    expose:
      - "4000"
    networks:
      - backend
    restart : unless-stopped
  mongodb:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - /home/rnc/koren/mongoRepl/mongo1:/data/db
    networks:
      - backend
    restart : unless-stopped
  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
    networks:
      - backend
networks:
  backend:
    driver: bridge
